name: build_multi

on:
  # pull_request:
  #  types: [closed]
  # push:
  #   branches: ["master"]
  pull_request:
    branches: ["**"]

jobs:
  build_multi_node:
    runs-on: ubuntu-20.04
    name: build_multi_node
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create Variables
        id: vars
        env:
          _repo: ${{github.repository}}
          _ref: ${{github.ref}}
        run: |
          echo "::set-output name=branch::$(echo ${_ref} | cut -d/ -f3)"
          echo "::set-output name=username::$(echo ${_repo} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=repo::$(echo ${_repo} | tr '[:upper:]' '[:lower:]')"

      - name: Printing Variables
        run: |
          echo "${{ steps.vars.outputs.branch }} && ${{github.ref}}"
          echo "${{ steps.vars.outputs.username }} && ${{github.repository}}"
          echo ${{ steps.vars.outputs.repo }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Buildx
        run: |
          cd docker && make build-node USERNAME=${{ steps.vars.outputs.username }} REPO=_acc TAG=dev VERSION=${{ steps.package-version.outputs.current-version }}

  build_multi_server:
    runs-on: ubuntu-20.04
    name: build_multi_server
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create Variables
        id: vars
        env:
          _repo: ${{github.repository}}
          _ref: ${{github.ref}}
        run: |
          echo "::set-output name=branch::$(echo ${_ref} | cut -d/ -f3)"
          echo "::set-output name=username::$(echo ${_repo} | cut -d/ -f1 | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=repo::$(echo ${_repo} | tr '[:upper:]' '[:lower:]')"

      - name: Printing Variables
        run: |
          echo "${{ steps.vars.outputs.branch }} && ${{github.ref}}"
          echo "${{ steps.vars.outputs.username }} && ${{github.repository}}"
          echo ${{ steps.vars.outputs.repo }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Buildx
        run: |
          cd docker && make build-server USERNAME=${{ steps.vars.outputs.username }} REPO=_acc TAG=dev VERSION=${{ steps.package-version.outputs.current-version }}
         
